### ISSUE TITLE
les liens ne se voient pas sur toutes les pages (violet sur fond violet)

### ISSUE THREAD

**Issue by r0one** [riseup-asso/ru#2]
![image](https://github.com/el-wynn/ru/assets/18699331/900b6d14-c63b-436e-94fd-2d636a99136d)

**Comment by qstdr** [comment]
Résolu en ajoutant des paramètres au theme 
admin/appearance/settings/tara
![Screenshot_20240727_234138_Brave.jpg](https://github.com/user-attachments/assets/b13480bc-a8d4-4953-bff0-cc239f3c251d)

**Comment by r0one** [comment]
merci beaucoup! à long terme il faudrait plutôt qu'on édite le code qui se trouve dans ce repo, mais ce code que tu nous donne nous indique la solution :)
